### ISSUE TITLE
Can't connect to hardly any Hosts

### ISSUE THREAD

**Issue by theShiZa** [selkies-project/docker-nvidia-glx-desktop#46]
Hi.

Please help. I used to use Vast.ai a few months ago & it was hit & miss with guessing which Host will run the GLX Desktop, but at least then I was having more success than now. Used exact same GLX Desktop settings now as back then.
Now it's the worst I've ever seen it. I get like 80% fail rate when trying Hosts. It's just a lotto. I got told to try Hosts running driver 535.129.03, which so far has been the only version that's worked, but in saying that, there's also been Hosts with same driver 535.129.03 & don't work. It's just a mixed bag of shit.

I just use the default GLX Desktop template at Vast. If the driver & cuda versions of 2 different Hosts are the same, what else could cause one to work & the other to fail?  
My internet speed itself is not the factor. This is a quick run-down of what I got today. I've also attached 2 log files of Status Logs & Debug Logs.

[m-8914.txt](https://github.com/selkies-project/docker-nvidia-glx-desktop/files/13603692/m-8914.txt)
[m-11864.txt](https://github.com/selkies-project/docker-nvidia-glx-desktop/files/13603693/m-11864.txt)

> SUCCESS ::
> 
>  ** m:88435 - 8x 4090 driver 535.129.03 running cuda 12.2 = YES, working.
> 
>  ** m:14018 - 8x 4090 driver 535.129.03 cuda 12.2 = YES, working.
> 
>  ** m:14791 - 1x 4090 driver 535.129.03 cuda 12.2 = YES, working.
> 
> 
> 
> 
> FAIL ::
> 
>  ** m:5150 - 8x 4090 driver 525.105.17 running cuda 12.0 = NO, entered Login info, "Connection Failed" with a RELOAD button.
> 
>  ** m:8914 DataCentre:18 - 8x 4090 driver 525.105.17 cuda 12.0 = NO, entered Login info, "Connection Failed" with a RELOAD button. I have Status Log & Debug Log for this one.
>  
>  ** m:8874 Host 54858 - 12x 4090 driver 535.104.05 cuda 12.2 = NO, error "Site Can't Be Reached".
> 
>  ** m:13471 Host 61247 - 12x 4090 driver 535.113.01 cuda 12.2 = NO, error "Site Can't Be Reached".
> 
>  ** m:11773 Host 61247 - 12x 4090 driver 535.129.03 running cuda 12.2 = NO, error, ""Error response from daemon: --storage-opt is supported only for overlay over xfs with 'pquota' mount option"".
> 
>  ** m:8965 DataCentre:18 - 8x 4090 driver 535.129.03 cuda 12.2 = NO, entered Login info, "Connection Failed" with a RELOAD button. (( 535.129.03 with cuda 12.2 & still didn't work? Something extra odd there as I've succeeded with those driver & cuda versions on other machine. )) I have Status Log & Debug Log for this one.
> 
>  ** m:9111 - 8x 4090 driver 535.129.03 cuda 12.2 = NO, entered Login info, "Connection Failed" with a RELOAD button. I have Status Log & Debug Log for this one. (( 535.129.03 with cuda 12.2 & still didn't work? Something extra odd there as I've succeeded with those driver & cuda versions on other machine. ))
> 
>  ** m:10921 Host 36803 - 8x 4090 driver 535.54.03 cuda 12.2 = NO, error "Site Can't Be Reached".
> 
>  ** m:8335 - 8x 4090 driver 545.23.08 cuda 12.3 = NO, error "Site Can't Be Reached".

Is this something we're going to deal with forever?  Just a lotto guessing game trying to find compatible Hosts which always change/get broken because of driver incompatibility ??  Why is it worse right now than ever before?  Also doesn't seem like driver version is the only thing at play here, as how can it be if 2 Hosts identical driver & cuda yet one works & other doesn't.

I've spoke with Vast Support at their site & Hosts at Vast Discord but it seems no one can just get this working in a more reliable way. What else can we try?  

Thanks for your time.

**Comment by ehfd** [comment]
I understand your issue and thank you for raising this.
Perhaps, docker-nvidia-egl-desktop would would better in more universal environments.

NVIDIA broke the mechanism for the glx desktop on 535 drivers and fixed them later on...

The TURN server requirement is that there are situations where the WebRTC peer-to-peer connection cannot be established because both the server and the client are behind some type of NAT (firewall).
The TURN server helps the server connect with the client.
Zoom, Parsec, and other services provide this TURN server themselves, but you need your own TURN server in this situation.

Specifying the TURN server solves this issue, and therefore you need your own TURN server.

https://github.com/selkies-project/selkies-gstreamer#using-a-turn-server

The above is a pretty comprehensive description of how you can set up your own coTURN server. You can possibly run this and expose both the frontend port (default is 3478) and the relay ports (a few or more ports with five digits, one per user) with Vast. You can also host your own coTURN server in any cloud VM you want.

https://www.metered.ca/tools/openrelay/

These people provide free TURN servers that you can try out to see if it solves most of the connection issues.

But the TURN server must be close to either the client or the server, or be in the path between both of them for optimal latency.

Please ask me more questions after digesting the above.

**Comment by ehfd** [comment]
> As for the TURN server, most all machines on vast have open ports and this template also filter requires that. This template exposes internal port 8080 and runs the web streaming server on that open port so the TURN server should not be required? That seems to be the case as it works on many machines without it.

@jsbcannell 

The port 8080 is for the web interface and WebSockets for relaying WebRTC signalling information. The WebRTC protocol is another thing from that and requires more ports, typically in the five-digit range. Containers without Host Networking are technically behind a firewall. That's why the TURN server requirement tends to be more common.

I might be able to prepare a template for a working TURN server template on VAST in some time if they provide some sponsorship resources to me.

**Comment by ehfd** [comment]
Please remind me on this in a couple days.
Bit busy now.

**Comment by ehfd** [comment]
> Whatever that involves it sounds excellent but I'm sure this will be too long in the future to benefit us anytime soon.

It's not that far away. If someone gives me some Vast credits, I can do it.

**Comment by ehfd** [comment]
> When attempting to do your TURN server steps, should I still be only trying on Hosts with driver versions <= 530.xx or >=535.129.03 for now??

Yes, these are two separate things. Both are requirements.

**Comment by ehfd** [comment]
Basically, you should be prepared to expose a few TCP ports and a few UDP ports. I need that to configure a TURN server in Vast or RunPod or CoreWeave.

**Comment by ehfd** [comment]
@theShiZa Hey. My work in the US is relevant to this so don't worry about that.

One suggestion is to use an Oracle Cloud's free VM instance because I found that there are only GPU nodes in VAST. That would work pretty well as a free TURN server.

**Comment by ehfd** [comment]
> What if I'll be uploading & downloading GB's or TB's of project files from the Vast Instance to/from Google Drive? Won't that be costing money if I got a VPS service?

You wouldn't need to do that. The TURN server only relays WebRTC, and it's definitely not a VPN. This is just for the relay ports in situations you can't open, and Oracle's free tier seems to be generous with egress.

> I was going to try using a spare laptop I have & set it up as a TURN server but I read the only way to get around my NAT is to set my laptop as DMZ from my router but that would mean it'd be very unsafe & not secure.

This is another very good way, but you would need to port forward certain outside-facing ports like you said using DMZ or other methods.

> _I found that there are only GPU nodes in VAST_

If VAST happened to have CPU-only instances or a way to provision a pod with only a small number of CPUs and a bit of RAM without GPUs, you wouldn't need a different VPN since the TURN server can be hosted this way. It would not be reasonable to allocate a GPU for a TURN server pod.

**Comment by ehfd** [comment]
Hey.
Neko has some containers but in maximum it's an EGL desktop alternative for now.
But I am willing to integrate more capabilities that Neko has to Selkies or even in the future merge them together.

**Comment by ehfd** [comment]
https://github.com/orgs/ai-dock/repositories

This container is based on my container and includes a TURN server.
Perhaps this may work better on RunPod and VAST.ai, because both platforms are not my main platform.

**Comment by ehfd** [comment]
@robballantyne
Speaking of which, are you interested in complementing each other?
I don't use VAST or Runpod nor I am interested in maintaining a huge lineup of container appliances, so we could specialize in different things.

**Comment by robballantyne** [comment]
@ehfd Absolutely.  My desktop container only exists because of your work.

I add quite a lot of other things because the target platforms allow one container per instance so it's unusual but necessary.

I think your gstreamer interface is incredible and I link back at every opportunity and I'll continue to do that as I add more appliances. I really appreciate what you've done.

**Comment by ehfd** [comment]
@robballantyne There's a Discord link on the top of README.md. If you aren't already there, we can talk there.
